#!/usr/bin/env python3
"""Adversarial unit tests for the Renovate runner-pin-line PR classifier."""

from __future__ import annotations

from copy import deepcopy
import unittest

from renovate_action_pr import classify


REPOSITORY = "0Bu/daikin-altherma-esp32"
HEAD = "a" * 40
PARENT = "b" * 40
OLD = "c" * 40
NEW = "d" * 40


def fixture() -> tuple[dict, dict, list[dict]]:
    pr = {
        "state": "open",
        "draft": False,
        "commits": 1,
        "changed_files": 1,
        "user": {"login": "0Bu"},
        "body": (
            "This PR has been generated by [Mend Renovate CLI]"
            "\n<!--renovate-debug:fixture-->"
        ),
        "head": {
            "sha": HEAD,
            "ref": "renovate/renovatebot-github-action-46.x",
            "repo": {"full_name": REPOSITORY},
        },
        "base": {"ref": "main", "repo": {"full_name": REPOSITORY}},
    }
    commit = {
        "sha": HEAD,
        "author": {"login": "renovate-bot"},
        "committer": {"login": "renovate-bot"},
        "commit": {
            "author": {
                "name": "Renovate Bot",
                "email": "renovate@whitesourcesoftware.com",
            },
            "committer": {
                "name": "Renovate Bot",
                "email": "renovate@whitesourcesoftware.com",
            },
        },
        "parents": [{"sha": PARENT}],
    }
    pages = [{
        "sha": HEAD,
        "files": [{
            "filename": ".github/workflows/renovate.yaml",
            "status": "modified",
            "additions": 1,
            "deletions": 1,
            "changes": 2,
            "patch": (
                "@@ -58 +58 @@\n"
                f"-      - uses: renovatebot/github-action@{OLD}  # v46.2.2\n"
                f"+      - uses: renovatebot/github-action@{NEW}  # v46.2.4"
            ),
        }],
    }]
    return pr, commit, pages


class RenovateActionPrTest(unittest.TestCase):
    def eligible(self, pr: dict, commit: dict, pages: list[dict]) -> bool:
        return classify(pr, commit, pages, REPOSITORY, HEAD)[0]

    def test_exact_action_digest_update_is_eligible(self) -> None:
        self.assertTrue(self.eligible(*fixture()))

    def test_multiple_or_non_renovate_pins_are_rejected(self) -> None:
        pr, commit, pages = fixture()
        pages[0]["files"][0].update({
            "additions": 2,
            "deletions": 2,
            "changes": 4,
            "patch": (
                "@@ -1,2 +1,2 @@\n"
                f"-      - uses: actions/checkout@{OLD}  # v7.0.0\n"
                f"-      - uses: actions/cache@{OLD}  # v6.0.0\n"
                f"+      - uses: actions/checkout@{NEW}  # v7.0.1\n"
                f"+      - uses: actions/cache@{NEW}  # v6.0.1"
            ),
        })
        self.assertFalse(self.eligible(pr, commit, pages))

    def test_wrong_repository_is_rejected(self) -> None:
        pr, commit, pages = fixture()
        pr["head"]["repo"]["full_name"] = "attacker/fork"
        self.assertFalse(self.eligible(pr, commit, pages))

    def test_non_renovate_or_unsafe_branch_is_rejected(self) -> None:
        for branch in ("feature/action-pin", "renovate/../action-pin"):
            with self.subTest(branch=branch):
                pr, commit, pages = fixture()
                pr["head"]["ref"] = branch
                self.assertFalse(self.eligible(pr, commit, pages))

    def test_non_renovate_body_is_rejected(self) -> None:
        pr, commit, pages = fixture()
        pr["body"] = "hand-written"
        self.assertFalse(self.eligible(pr, commit, pages))

    def test_non_single_integer_commit_count_is_rejected(self) -> None:
        for commits in (2, True, "1"):
            with self.subTest(commits=commits):
                pr, commit, pages = fixture()
                pr["commits"] = commits
                self.assertFalse(self.eligible(pr, commit, pages))

    def test_wrong_commit_identity_or_signature_is_rejected(self) -> None:
        for mutation in ("login", "email"):
            with self.subTest(mutation=mutation):
                pr, commit, pages = fixture()
                if mutation == "login":
                    commit["committer"]["login"] = "0Bu"
                else:
                    commit["commit"]["author"]["email"] = "renovate@example.invalid"
                self.assertFalse(self.eligible(pr, commit, pages))

    def test_head_mismatch_is_rejected(self) -> None:
        pr, commit, pages = fixture()
        commit["sha"] = "e" * 40
        self.assertFalse(self.eligible(pr, commit, pages))

    def test_non_allowlisted_paths_are_rejected(self) -> None:
        for filename in (
            "main/main.cpp",
            ".github/workflows/build.yml",
            ".github/workflows/third-party.yaml",
        ):
            with self.subTest(filename=filename):
                pr, commit, pages = fixture()
                pages[0]["files"][0]["filename"] = filename
                self.assertFalse(self.eligible(pr, commit, pages))

    def test_added_or_renamed_workflow_is_rejected(self) -> None:
        pr, commit, pages = fixture()
        pages[0]["files"][0]["status"] = "added"
        self.assertFalse(self.eligible(pr, commit, pages))
        pr, commit, pages = fixture()
        pages[0]["files"][0]["previous_filename"] = ".github/workflows/old.yaml"
        self.assertFalse(self.eligible(pr, commit, pages))

    def test_missing_patch_is_rejected(self) -> None:
        pr, commit, pages = fixture()
        del pages[0]["files"][0]["patch"]
        self.assertFalse(self.eligible(pr, commit, pages))

    def test_arbitrary_workflow_edit_is_rejected(self) -> None:
        pr, commit, pages = fixture()
        pages[0]["files"][0]["patch"] = "@@ -1 +1 @@\n-timeout-minutes: 20\n+timeout-minutes: 30"
        self.assertFalse(self.eligible(pr, commit, pages))

    def test_action_identity_change_is_rejected(self) -> None:
        pr, commit, pages = fixture()
        pages[0]["files"][0]["patch"] = (
            "@@ -1 +1 @@\n"
            f"-      - uses: actions/checkout@{OLD}  # v7.0.0\n"
            f"+      - uses: attacker/checkout@{NEW}  # v7.0.1"
        )
        self.assertFalse(self.eligible(pr, commit, pages))

    def test_tag_pin_is_rejected(self) -> None:
        pr, commit, pages = fixture()
        pages[0]["files"][0]["patch"] = (
            "@@ -1 +1 @@\n"
            f"-      - uses: actions/checkout@{OLD}  # v7.0.0\n"
            "+      - uses: actions/checkout@v7.0.1"
        )
        self.assertFalse(self.eligible(pr, commit, pages))

    def test_comment_only_update_is_rejected(self) -> None:
        pr, commit, pages = fixture()
        pages[0]["files"][0]["patch"] = (
            "@@ -1 +1 @@\n"
            f"-      - uses: actions/checkout@{OLD}  # v7.0.0\n"
            f"+      - uses: actions/checkout@{OLD}  # v7.0.1"
        )
        self.assertFalse(self.eligible(pr, commit, pages))

    def test_mixed_action_and_other_edit_is_rejected(self) -> None:
        pr, commit, pages = fixture()
        pages[0]["files"][0].update({
            "additions": 2,
            "deletions": 2,
            "changes": 4,
            "patch": (
                "@@ -1,2 +1,2 @@\n"
                f"-      - uses: actions/checkout@{OLD}  # v7.0.0\n"
                "-      timeout-minutes: 10\n"
                f"+      - uses: actions/checkout@{NEW}  # v7.0.1\n"
                "+      timeout-minutes: 20"
            ),
        })
        self.assertFalse(self.eligible(pr, commit, pages))

    def test_file_count_and_boolean_counts_are_rejected(self) -> None:
        pr, commit, pages = fixture()
        pr["changed_files"] = 2
        self.assertFalse(self.eligible(pr, commit, pages))
        pr, commit, pages = fixture()
        pages[0]["files"][0]["additions"] = True
        self.assertFalse(self.eligible(pr, commit, pages))

    def test_malformed_nested_metadata_is_rejected_without_exception(self) -> None:
        pr, commit, pages = fixture()
        pr["base"] = None
        self.assertFalse(self.eligible(pr, commit, pages))

    def test_patch_page_from_another_head_is_rejected(self) -> None:
        pr, commit, pages = fixture()
        pages[0]["sha"] = "e" * 40
        self.assertFalse(self.eligible(pr, commit, pages))

    def test_fixture_mutations_do_not_leak(self) -> None:
        first = fixture()
        second = deepcopy(first)
        second[0]["head"]["ref"] = "feature/not-renovate"
        self.assertTrue(self.eligible(*first))
        self.assertFalse(self.eligible(*second))


if __name__ == "__main__":
    unittest.main()
