#!/usr/bin/env python3
"""Generate native Codex registrations from the maintained runner-neutral sources."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import subprocess
import sys

TOOL_ROOT = Path(__file__).resolve().parents[2]
ROOT = Path(os.environ.get("AGENT_CONFIG_ROOT", TOOL_ROOT)).resolve()
HEADER = "# Generated by tools/agent-config/export-subagents.py; do not edit.\n"
MANIFEST = ".codex/generated.json"


def digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def validate_sources() -> None:
    env = dict(os.environ, AGENT_CONFIG_ROOT=str(ROOT))
    for checker in ("check_toml.py", "check_hooks.py"):
        result = subprocess.run(
            [sys.executable, str(TOOL_ROOT / "tools/agent-config" / checker)],
            env=env, capture_output=True, text=True, check=False,
        )
        if result.returncode:
            raise ValueError(result.stderr.strip() or f"{checker} failed")


def outputs() -> dict[str, bytes]:
    sources = [".mcp.json", ".agents/hooks.json"]
    sources += [p.relative_to(ROOT).as_posix() for p in sorted((ROOT / ".agents/agents").glob("*.toml"))]
    mcp = json.loads((ROOT / ".mcp.json").read_text(encoding="utf-8"))["mcpServers"]["context7"]
    config = HEADER + "\n[agents]\nmax_concurrent_threads_per_session = 3\n"
    config += "\n[mcp_servers.context7]\n"
    config += f"command = {json.dumps(mcp['command'])}\nargs = {json.dumps(mcp['args'])}\n"
    guards = json.loads((ROOT / ".agents/hooks.json").read_text(encoding="utf-8"))["safety-guards"]
    hooks = {event: groups for event, groups in guards.items() if event != "Stop"}
    hooks["Stop"] = [{"hooks": guards["Stop"]}]
    result = {
        ".codex/config.toml": config.encode(),
        ".codex/hooks.json": (json.dumps({"hooks": hooks}, indent=2) + "\n").encode(),
    }
    for source in sources[2:]:
        result[".codex/agents/" + Path(source).name] = HEADER.encode() + (ROOT / source).read_bytes()
    manifest = {
        "generated_by": "tools/agent-config/export-subagents.py",
        "schema_version": 1,
        "sources": {source: digest((ROOT / source).read_bytes()) for source in sources},
        "outputs": {path: digest(data) for path, data in sorted(result.items())},
    }
    result[MANIFEST] = (json.dumps(manifest, indent=2, sort_keys=True) + "\n").encode()
    return result


def check_paths(result: dict[str, bytes]) -> None:
    for relative in result:
        path = ROOT / relative
        for ancestor in (path, *path.parents):
            if ancestor == ROOT:
                break
            if ancestor.is_symlink():
                raise ValueError(f"generated path must not be a symlink: {relative}")
        if path.exists() and not path.is_file():
            raise ValueError(f"generated path must be a regular file: {relative}")
    agent_dir = ROOT / ".codex/agents"
    if agent_dir.exists():
        extras = {p.relative_to(ROOT).as_posix() for p in agent_dir.iterdir()} - set(result)
        if extras:
            raise ValueError("unregistered native reviewer files: " + ", ".join(sorted(extras)))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="regenerate project-local adapters")
    mode.add_argument("--check", action="store_true", help="check byte-for-byte generated parity")
    args = parser.parse_args()
    try:
        validate_sources()
        result = outputs()
        check_paths(result)
        changed = [path for path, data in result.items() if not (ROOT / path).exists() or (ROOT / path).read_bytes() != data]
        if args.check and changed:
            raise ValueError("generated Codex registration drift: " + ", ".join(changed) + "; run scripts/setup-codex.sh")
        if args.write:
            previous = {}
            if (ROOT / MANIFEST).exists():
                previous = json.loads((ROOT / MANIFEST).read_text(encoding="utf-8")).get("outputs", {})
            for relative in changed:
                path = ROOT / relative
                if relative != MANIFEST and path.exists() and previous.get(relative) != digest(path.read_bytes()):
                    raise ValueError(f"refusing to overwrite locally modified or unowned file: {relative}; review it first")
            for relative in changed:
                path = ROOT / relative
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_bytes(result[relative])
        print(f"codex-registration: {len(result)} generated files {'regenerated' if args.write else 'match canonical sources'}")
        print("codex-registration: registration is not hook trust, live dispatch or reviewer sandbox evidence")
        return 0
    except (OSError, ValueError, KeyError) as exc:
        print(f"codex-registration: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
