#!/usr/bin/env python3
"""Generate main/def/<profile>.hpp value-definition tables from classic Altherma def/* files.

The classic Altherma monitor firmware stores each model's registers as C rows like:

    {0x60,7,105,2,1,"Sollwert Brauchwasser"},
    //{0x00,0,802,0,-1,"*Kältemittel Typ"},   (commented = not queried by default)

This script parses those rows (commented or not) and emits an inline constexpr daik::ValueDef[]
array so the whole catalog is embedded and the web UI can toggle individual values at runtime
(the "commented" state becomes the default val_mask, not a compile-time exclusion).

Usage:
    tools/gen_defs.py --name altherma3_r_erga --out main/def \\
        "/path/to/altherma-defs/German/Altherma(ERGA E EHV-EHB-EHVZ E_EJ series 04-08kW).h"

Then wire the new profile into main/def/registry.hpp (id -> array) and the /models catalog.
"""
import argparse
import os
import re
import sys

ROW = re.compile(
    r'^\s*(//)?\s*\{\s*(0x[0-9a-fA-F]+|\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(-?\d+)\s*,\s*"((?:[^"\\]|\\.)*)"\s*\}'
)


def parse(path):
    rows = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            m = ROW.match(line)
            if not m:
                continue
            commented = m.group(1) == "//"
            reg, off, conv, size, typ, label = m.group(2, 3, 4, 5, 6, 7)
            rows.append((reg, off, conv, size, typ, label, commented))
    return rows


def emit(name, rows, src):
    out = []
    out.append("#pragma once")
    out.append(f"// GENERATED by tools/gen_defs.py from:\n//   {os.path.basename(src)}")
    out.append("// Do not edit by hand — re-run the generator. Rows carry the whole catalog; the")
    out.append("// `default_on` comment marks the source's default-enabled values (initial val_mask).")
    out.append('#include "../logic/value_def.hpp"')
    out.append("")
    out.append("namespace daik::def {")
    out.append("")
    out.append(f"inline constexpr ValueDef {name}[] = {{")
    for reg, off, conv, size, typ, label, commented in rows:
        tag = "" if commented else "  // default_on"
        safe = label.replace('"', '\\"')
        out.append(f'    {{{reg}, {off}, {conv}, {size}, {typ}, "{safe}"}},{tag}')
    out.append("};")
    out.append("")
    out.append("} // namespace daik::def")
    out.append("")
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--name", required=True, help="profile id / array name (C identifier)")
    ap.add_argument("--out", default="main/def", help="output directory")
    ap.add_argument("src", help="classic Altherma def/*.h file")
    a = ap.parse_args()

    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", a.name):
        sys.exit(f"--name must be a C identifier, got {a.name!r}")
    rows = parse(a.src)
    if not rows:
        sys.exit(f"no value rows parsed from {a.src}")
    os.makedirs(a.out, exist_ok=True)
    dst = os.path.join(a.out, f"{a.name}.hpp")
    with open(dst, "w", encoding="utf-8") as f:
        f.write(emit(a.name, rows, a.src))
    n_on = sum(1 for r in rows if not r[6])
    print(f"wrote {dst}: {len(rows)} values ({n_on} default-on)")


if __name__ == "__main__":
    main()
