#pragma once
// Value converters — raw register bytes -> typed reading. Ported from ESPAltherma
// include/converters.h. This is the single riskiest piece of the port (a wrong sign/scale/
// endianness silently corrupts a reading), so it is IDF-free and unit-tested per converter id
// in test/test_logic.cpp against the ESPAltherma reference outputs.
//
// STATUS: the numeric converters verified against ESPAltherma (100-111 + the refrigerant
// pressure->temperature curves) are ported exactly below. The large set of enum/label
// converters (operating-mode, on/off, fan-step, error codes, …) is generated by
// tools/gen_defs.py alongside the def profiles; convert() returns Reading{unimpl=true} for a
// conv id not yet ported, mirroring ESPAltherma's "conv XXX not avail." so the value is simply
// skipped rather than wrong.
#include <cmath>
#include <cstdint>
#include "value_def.hpp"
#include "registers.hpp"

namespace daik {

struct Reading {
    bool   ok      = false;   // a numeric value is present
    bool   unimpl  = false;   // converter not implemented for this id
    double value   = 0.0;
    // For enum/string converters, text[] holds the decoded label (else empty).
    char   text[24] = {0};
};

// ── Refrigerant pressure -> saturation temperature (°C). RType: 801=R410A, 802=R32, 803=R22 ──
inline double press2temp_r410a(double d) {
    return -8.4448460086362E-07*d*d*d*d*d*d + 0.000112833751855216*d*d*d*d*d
           - 0.00584955138495273*d*d*d*d + 0.149130933664499*d*d*d
           - 1.99373679674187*d*d + 16.0504901396224*d - 53.2854030662239;
}
inline double press2temp_r22(double d) {
    return -5.0232146925414E-06*d*d*d*d*d*d + 0.000475561916201275*d*d*d*d*d
           - 0.0175087997648461*d*d*d*d + 0.318620413943417*d*d*d
           - 3.0844373741869*d*d + 19.0217687284902*d - 42.3282361912494;
}
inline double press2temp(double d, int rtype = 802) {
    if (rtype == 801) return press2temp_r410a(d);
    if (rtype == 803) return press2temp_r22(d);
    return -2.6989493795556E-07*d*d*d*d*d*d + 4.26383417104661E-05*d*d*d*d*d
           - 0.00262978346547749*d*d*d*d + 0.0805858127503585*d*d*d
           - 1.31924457284073*d*d + 13.4157368435437*d - 51.1813342993155;
}

// Convert one value. `data` points at the value's bytes inside the reply payload.
inline Reading convert(const ValueDef& def, const uint8_t* data, int rtype = 802) {
    Reading r;
    const int n = def.size;
    switch (def.conv) {
        // Signed/unsigned integers (ESPAltherma 101/102) and fixed-point scales (103-111).
        case 101: r.value = (double)read_int(data, n, false);              r.ok = true; break;
        case 102: r.value = (double)read_int(data, n, true);               r.ok = true; break;
        case 103: r.value = (double)read_int(data, n, false) / 256.0;      r.ok = true; break;
        case 104: r.value = (double)read_int(data, n, true) / 256.0;       r.ok = true; break;
        case 105: r.value = (double)read_int(data, n, false) * 0.1;        r.ok = true; break;
        case 106: r.value = (double)read_int(data, n, true) * 0.1;         r.ok = true; break;
        case 107: r.value = (double)read_int(data, n, false) * 0.1;        r.ok = (r.value != -3276.8); break;
        case 108: r.value = (double)read_int(data, n, true) * 0.1;         r.ok = (r.value != -3276.8); break;
        case 109: r.value = (double)read_int(data, n, false) / 256.0 * 2;  r.ok = true; break;
        case 110: r.value = (double)read_int(data, n, true) / 256.0 * 2;   r.ok = true; break;
        case 111: r.value = (double)read_int(data, n, true) * 0.5;         r.ok = true; break;
        // 152: unsigned integer count/step (fan step, pump speed, counts).
        case 152: r.value = (double)read_int(data, n, false);              r.ok = true; break;
        // 161: signed current-transformer reading (A).
        case 161: r.value = (double)read_int(data, n, true);               r.ok = true; break;
        // 405: low/high pressure raw -> saturation temperature (°C).
        case 405: r.value = press2temp((double)read_int(data, n, false) * 0.1, rtype); r.ok = true; break;
        default:
            // Enum/label converters (217/203/204/211/300-3xx/…) are generated; not yet ported.
            r.unimpl = true;
            break;
    }
    return r;
}

// Home Assistant hints derived from the converter id (extended by the generator).
inline const char* unit_for_conv(int conv) {
    switch (conv) {
        case 103: case 104: case 105: case 106: case 107: case 108:
        case 114: case 118: case 119: case 405: return "°C";
        case 161: return "A";
        default:  return "";
    }
}
inline const char* device_class_for_conv(int conv) {
    switch (conv) {
        case 103: case 104: case 105: case 106: case 107: case 108:
        case 114: case 118: case 119: case 405: return "temperature";
        case 161: return "current";
        default:  return "";
    }
}

} // namespace daik
