#pragma once
// Value converters — raw register bytes -> typed reading. This is the single riskiest piece of the
// port (a wrong sign/scale/endianness silently corrupts a reading), so it is IDF-free and unit-
// tested per converter id in test/test_logic.cpp.
//
// Semantics (cross-checked against two independent X10A implementations): convs 101-111 read a
// SIGNED 16-bit field, 151-165 an UNSIGNED one; within a group the id's parity selects endianness
// (flag 0 = little-endian, flag 1 = big-endian). A 1-byte field is read from data[0]. The large set
// of enum/label converters (operating-mode, on/off, fan-step, error codes) is generated by
// tools/gen_defs.py alongside the def profiles; convert() returns Reading{unimpl=true} for a conv id
// not yet ported, so the value is simply skipped rather than reported wrong.
#include <cmath>
#include <cstdint>
#include "value_def.hpp"
#include "registers.hpp"

namespace daik {

struct Reading {
    bool   ok      = false;   // a numeric value is present
    bool   unimpl  = false;   // converter not implemented for this id
    double value   = 0.0;
    // For enum/string converters, text[] holds the decoded label (else empty).
    char   text[24] = {0};
};

// ── Refrigerant pressure -> saturation temperature (°C). RType: 801=R410A, 802=R32, 803=R22 ──
inline double press2temp_r410a(double d) {
    return -8.4448460086362E-07*d*d*d*d*d*d + 0.000112833751855216*d*d*d*d*d
           - 0.00584955138495273*d*d*d*d + 0.149130933664499*d*d*d
           - 1.99373679674187*d*d + 16.0504901396224*d - 53.2854030662239;
}
inline double press2temp_r22(double d) {
    return -5.0232146925414E-06*d*d*d*d*d*d + 0.000475561916201275*d*d*d*d*d
           - 0.0175087997648461*d*d*d*d + 0.318620413943417*d*d*d
           - 3.0844373741869*d*d + 19.0217687284902*d - 42.3282361912494;
}
inline double press2temp(double d, int rtype = 802) {
    if (rtype == 801) return press2temp_r410a(d);
    if (rtype == 803) return press2temp_r22(d);
    return -2.6989493795556E-07*d*d*d*d*d*d + 4.26383417104661E-05*d*d*d*d*d
           - 0.00262978346547749*d*d*d*d + 0.0805858127503585*d*d*d
           - 1.31924457284073*d*d + 13.4157368435437*d - 51.1813342993155;
}

// Convert one value. `data` points at the value's bytes inside the reply payload.
inline Reading convert(const ValueDef& def, const uint8_t* data, int rtype = 802) {
    Reading r;
    const int n = def.size;
    switch (def.conv) {
        // Signed 16-bit; even id = little-endian, odd = big-endian; then a fixed-point scale.
        case 101: r.value = read_s16(data, n, false);              r.ok = true; break;
        case 102: r.value = read_s16(data, n, true);               r.ok = true; break;
        case 103: r.value = read_s16(data, n, false) / 256.0;      r.ok = true; break;
        case 104: r.value = read_s16(data, n, true) / 256.0;       r.ok = true; break;
        case 105: r.value = read_s16(data, n, false) * 0.1;        r.ok = true; break;   // temperature (LE)
        case 106: r.value = read_s16(data, n, true) * 0.1;         r.ok = true; break;
        case 107: r.value = read_s16(data, n, false) * 0.1;        r.ok = (r.value != -3276.8); break;
        case 108: r.value = read_s16(data, n, true) * 0.1;         r.ok = (r.value != -3276.8); break;
        case 109: r.value = read_s16(data, n, false) / 256.0 * 2.0; r.ok = true; break;
        case 110: r.value = read_s16(data, n, true) / 256.0 * 2.0;  r.ok = true; break;
        case 111: r.value = read_s16(data, n, true) * 0.5;         r.ok = true; break;
        // Unsigned 16-bit (counts / steps / CT current).
        case 151: r.value = read_u16(data, n, false);             r.ok = true; break;
        case 152: r.value = read_u16(data, n, true);              r.ok = true; break;
        case 161: r.value = read_u16(data, n, true) * 0.5;        r.ok = true; break;    // CT current (0.5 A)
        // Refrigerant pressure raw (signed LE ×0.1) -> saturation temperature (°C).
        case 405: r.value = press2temp(read_s16(data, n, false) * 0.1, rtype); r.ok = true; break;
        default:
            // Enum/label converters (217/203/204/211/300-3xx/…) are generated; not yet ported.
            r.unimpl = true;
            break;
    }
    return r;
}

// Home Assistant hints from the value's dataType field — the classic Altherma unit code
// (1 = °C temperature, 2 = bar pressure, 3 = A current, -1/other = generic; current is often
// carried in the label as "(A)" and left generic). Cross-checked against a second X10A
// implementation.
inline const char* unit_for_datatype(int dataType) {
    switch (dataType) {
        case 1:  return "°C";
        case 2:  return "bar";
        case 3:  return "A";
        default: return "";
    }
}
inline const char* device_class_for_datatype(int dataType) {
    switch (dataType) {
        case 1:  return "temperature";
        case 2:  return "pressure";
        case 3:  return "current";
        default: return "";
    }
}

} // namespace daik
